edition = "2021"
# (optional) other config...
attr_value_brace_style = "WhenRequired" # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
macro_names = ["leptos::view, view"]    # Macro names which will be formatted
